# Generated by Django 2.2.6 on 2020-11-09 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_directory', '0002_auto_20201109_1744'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subjects',
            old_name='email_address',
            new_name='teacher',
        ),
    ]
