# Generated by Django 2.2.6 on 2020-11-10 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_directory', '0003_auto_20201109_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
